include:
  - ./docker-compose.yml

services:
  rmf2-vda5050-master:
    build:
      context: ./services/rmf2_vda5050_master
      dockerfile: Dockerfile
    ports:
      - "${RMF2_VM_PORT:-8000}:8000"
    depends_on:
      mqtt-broker:
        condition: service_healthy
    networks:
      - rmf2-net
    environment:
      MODE: staging
      RMF2_VM__MQTT_BROKER: "tcp://mqtt-broker:${MQTT_PORT:-1883}"
      RMF2_VM__AMQP__ENABLED: true
      RMF2_VM__AMQP__URL: "amqp://guest:guest@amqp-broker/"
      RMF2_VM__AMQP__EXCHANGE: rmf2
      RMF2_VM__MASTER_MQTT_CLIENT_ID: "example-master"
      RMF2_VM__HOST: "0.0.0.0"
      RMF2_VM__PORT: "8000"
