[[agvs]]
manufacturer = "Manufacturer"
serial_number = "1"

[[agvs]]
manufacturer = "Manufacturer"
serial_number = "2"

[[agvs]]
manufacturer = "Manufacturer"
serial_number = "3"

[[agvs]]
manufacturer = "Manufacturer"
serial_number = "4"

[[agvs]]
manufacturer = "Manufacturer"
serial_number = "5"
